package com.example.services

import org.slf4j.LoggerFactory
import io.ktor.server.application.*
import io.ktor.util.*

/**
 * Service to manage paint colours mapping
 */
class PaintColourService {
    private val logger = LoggerFactory.getLogger(PaintColourService::class.java)
    
    // Paint colour mapping - these are just representative colors for the UI
    private val paintColourMap = mapOf(
        // Base paints
        "Corax White" to "#f5f5f5",
        "Grey Seer" to "#d9d9d9",
        "Celestra Grey" to "#b0b7bb",
        "Averland Sunset" to "#fdb825",
        "Jokaero Orange" to "#f36b21",
        "Khorne Red" to "#6a0f19",
        "Mephiston Red" to "#a32026",
        "Gal Vorbak Red" to "#511517",
        "Barak-Nar Burgundy" to "#481d29",
        "Screamer Pink" to "#92304e",
        "Daemonette Hide" to "#695f7c",
        "Phoenician Purple" to "#4d215e",
        "Naggaroth Night" to "#352544",
        "Caledor Sky" to "#3b6691",
        "Macragge Blue" to "#0d407f",
        "Kantor Blue" to "#112860",
        "Night Lords Blue" to "#142b52",
        "Thousand Sons Blue" to "#24496a",
        "Stegadon Scale Green" to "#034861",
        "Lupercal Green" to "#0b312d",
        "Incubi Darkness" to "#0f2e2a",
        "Death Guard Green" to "#7b8969",
        "Deathworld Forest" to "#5a6c3e",
        "Castellan Green" to "#3c4a2d",
        "Death Korps Drab" to "#5e5c4b",
        "Waaagh! Flesh" to "#2e4339",
        "Caliban Green" to "#003d28",
        "Nocturne Green" to "#062a23",
        "Wraithbone" to "#e8e1d3",
        "Morghast Bone" to "#bcb195",
        "Zandri Dust" to "#a99058",
        "XV-88" to "#7f4f30",
        "Steel Legion Drab" to "#5b5334",
        "Mournfang Brown" to "#5b2e20",
        "Rhinox Hide" to "#44271a",
        "Dryad Bark" to "#2e221a",
        "Ionrach Skin" to "#d7c59d",
        "Rakarth Flesh" to "#cbc2b6",
        "Ratskin Flesh" to "#b78b6a",
        "Bugman's Glow" to "#934532",
        "Catachan Flesh" to "#6a322f",
        "The Fang" to "#436177",
        "Mechanicus Standard Grey" to "#3e4144",
        "Corvus Black" to "#2f3032",
        "Abaddon Black" to "#231f20",
        "Grey Knights Steel" to "#8c9ca5",
        "Iron Hands Steel" to "#575b5e",
        "Leadbelcher" to "#6d7073",
        "Iron Warriors" to "#494c4f",
        "Retributor Armour" to "#b48c30",
        "Balthasar Gold" to "#a36b2e",
        "Screaming Bell" to "#955335",
        "Warplock Bronze" to "#4d392b",
        "Runelord Brass" to "#937866",
        "Orruk Flesh" to "#849a48",
        "Hobgrot Hide" to "#c28a58",
        "Thondia Brown" to "#876f5d",
        
        // Contrast paints
        "Bad Moon Yellow" to "#ffd100",
        "Imperial Fist" to "#ffc700",
        "Ironjawz Yellow" to "#ffa800",
        "Iyanden Yellow" to "#ffd800",
        "Nazdreg Yellow" to "#d1a000",
        "Magmadroth Flame" to "#ff4500",
        "Gryph-Hound Orange" to "#ff7300",
        "Baal Red" to "#cc0000",
        "Blood Angels Red" to "#bf0a0a",
        "Flesh Tearers Red" to "#8b0000",
        "Doomfire Magenta" to "#cc00cc",
        "Volupus Pink" to "#ff00ff",
        "Sigvald Burgundy" to "#800020",
        "Magos Purple" to "#6a0dad",
        "Luxion Purple" to "#9400d3",
        "Leviathan Purple" to "#8a2be2",
        "Shyish Purple" to "#663399",
        "Pylar Glacier" to "#add8e6",
        "Frostheart" to "#87ceeb",
        "Talassar Blue" to "#0099cc",
        "Asurmen Blue" to "#1e90ff",
        "Celestium Blue" to "#0000cd",
        "Ultramarines Blue" to "#1155aa",
        "Leviadon Blue" to "#003366",
        "Stormfiend" to "#607d8b",
        "Karandras Green" to "#008000",
        "Striking Scorpion Green" to "#00a000",
        "Mantis Warriors Green" to "#00cc00",
        "Plaguebearer Flesh" to "#b8b75c",
        "Gutrippa Flesh" to "#8e9b5e",
        "Militarum Green" to "#4d6d50",
        "Creed Camo" to "#4b5320",
        "Dark Angels Green" to "#003300",
        "Hexwraith Flame" to "#00ff00",
        "Briar Queen Chill" to "#00ffff",
        "Nighthaunt Gloom" to "#86a0a3",
        "Gryph-Charger Grey" to "#708090",
        "Space Wolves Grey" to "#526280",
        "Skeleton Horde" to "#daa520",
        "Aggaros Dunes" to "#b8860b",
        "Garaghak's Sewer" to "#8b4513",
        "Snakebite Leather" to "#8b4513",
        "Gore-Grunta Fur" to "#8b4513",
        "Aethermatic Blue" to "#00ccff",
        "Kroxigor Scales" to "#00868b",
        "Akhelian Green" to "#008080",
        "Terradon Turquoise" to "#40e0d0",
        "Aeldari Emerald" to "#008a5e",
        "Ork Flesh" to "#6b8e23",
        "Warp Lightning" to "#2ca852",
        "Ratling Grime" to "#704214",
        "Wyldwood" to "#654321",
        "Cygor Brown" to "#5e3720",
        "Guilliman Flesh" to "#f0caa8",
        "Fyreslayer Flesh" to "#e8a17e",
        "Darkoath Flesh" to "#cc9966",
        "Dreadful Visage" to "#e5dbcc",
        "Apothecary White" to "#f8f8ff",
        "Basilicanum Grey" to "#696969",
        "Black Templar" to "#232323",
        "Black Legion" to "#1a1a1a",
        
        // Layer paints 
        "White Scar" to "#ffffff",
        "Ulthuan Grey" to "#e9e9e7",
        "Dorn Yellow" to "#fff700",
        "Phalanx Yellow" to "#ffeb00",
        "Flash Gitz Yellow" to "#ffff00",
        "Yriel Yellow" to "#ffdd00",
        "Lugganath Orange" to "#ff9933",
        "Fire Dragon Bright" to "#ff5500",
        "Troll Slayer Orange" to "#ff5500",
        "Squig Orange" to "#ff3300",
        "Wild Rider Red" to "#ff3300",
        "Evil Sunz Scarlet" to "#db0a00",
        "Wazdakka Red" to "#990000",
        "Word Bearers Red" to "#660000",
        "Fulgrim Pink" to "#ffc0cb",
        "Emperor's Children" to "#ffc0cb",
        "Pink Horror" to "#ff66cc",
        "Slaanesh Grey" to "#c9c3c2",
        "Warpfiend Grey" to "#a8a8a8",
        "Dechala Lilac" to "#cc99ff",
        "Kakophoni Purple" to "#9966cc",
        "Genestealer Purple" to "#7d4dc1",
        "Xereus Purple" to "#660099",
        "Blue Horror" to "#99ccff",
        "Hoeth Blue" to "#4d80e6",
        "Lothern Blue" to "#33a1c9",
        "Calgar Blue" to "#3366cc",
        "Teclis Blue" to "#0066cc",
        "Alaitoc Blue" to "#0044aa",
        "Altdorf Guard Blue" to "#003399",
        "Baharroth Blue" to "#99ffff",
        "Temple Guard Blue" to "#00cccc",
        "Ahriman Blue" to "#006699",
        "Sotek Green" to "#008080",
        "Gauss Blaster Green" to "#00cc99",
        "Sybarite Green" to "#00cc66",
        "Kabalite Green" to "#009966",
        "Nurgling Green" to "#7cb342",
        "Elysian Green" to "#8bc34a",
        "Ogryn Camo" to "#a5d24a",
        "Straken Green" to "#669900",
        "Loren Forest" to "#556b2f",
        "Sons of Horus Green" to "#3b7b6e",
        "Vulkan Green" to "#004d40",
        "Skarsnik Green" to "#b2df8a",
        "Moot Green" to "#50b050",
        "Warboss Green" to "#2e8b57",
        "Warpstone Glow" to "#009933",
        "Screaming Skull" to "#f7f3e3",
        "Ushabti Bone" to "#d5c89e",
        "Krieg Khaki" to "#c3bcaa",
        "Karak Stone" to "#ba9269",
        "Baneblade Brown" to "#887142",
        "Gorthor Brown" to "#7f5c36",
        "Zamesi Desert" to "#d4a340",
        "Tallarn Sand" to "#bb7f41",
        "Deathclaw Brown" to "#ce7c4c",
        "Balor Brown" to "#955f37",
        "Tau Light Ochre" to "#c19958",
        "Skrag Brown" to "#895624",
        "Tuskgor Fur" to "#703626",
        "Doombull Brown" to "#5f1d19",
        "Pallid Wych Flesh" to "#f2e8d5",
        "Deepkin Flesh" to "#d9c8b0",
        "Flayed One Flesh" to "#f0dbc3",
        "Ungor Flesh" to "#e3ba86",
        "Kislev Flesh" to "#d7a36e",
        "Bestigor Flesh" to "#c8855a",
        "Cadian Fleshtone" to "#b36c40",
        "Knight-Questor Flesh" to "#a15736",
        "Bloodreaver Flesh" to "#93452e",
        "Fenrisian Grey" to "#8ba1ad",
        "Russ Grey" to "#5a7685",
        "Thunderhawk Blue" to "#4a7179",
        "Dark Reaper" to "#3e5055",
        "Administratum Grey" to "#a8a9ad",
        "Dawnstone" to "#7e7f7b",
        "Stormvermin Fur" to "#696664",
        "Eshin Grey" to "#4d4d4c",
        "Skavenblight Dinge" to "#4a4945",
        "Stormhost Silver" to "#f5f5f5",
        "Runefang Steel" to "#adb6c4",
        "Ironbreaker" to "#8c9299",
        "Liberator Gold" to "#d4af37",
        "Auric Armour Gold" to "#e6be53",
        "Gehenna's Gold" to "#b27b3c",
        "Fulgurite Copper" to "#a65f3a",
        "Hashut Copper" to "#914f40",
        "Skullcrusher Brass" to "#7e6240",
        "Brass Scorpion" to "#8a4f39",
        "Sycorax Bronze" to "#a78b6a",
        "Castellax Bronze" to "#6b5d4e",
        "Canoptek Alloy" to "#a1a3a6",
        
        // Shade paints
        "Casandora Yellow" to "#ffb732",
        "Fuegan Orange" to "#f68534",
        "Berserker Bloodshade" to "#c81912",
        "Carroburg Crimson" to "#a63a50",
        "Targor Rageshade" to "#861a21",
        "Druchii Violet" to "#6c476f",
        "Tyran Blue" to "#295086",
        "Drakenhof Nightshade" to "#234685",
        "Athonian Camoshade" to "#4a5c2f",
        "Biel-Tan Green" to "#2b583d",
        "Coelia Greenshade" to "#1d7468",
        "Kroak Green" to "#136e49",
        "Poxwalker" to "#556b48",
        "Mortarion Grime" to "#3b4d37",
        "Seraphim Sepia" to "#b58a3d",
        "Reikland Fleshshade" to "#a75523",
        "Agrax Earthsahde" to "#6b5040",
        "Soulblight Grey" to "#5c5c67",
        "Nuln Oil" to "#383838",
        
        // Dry paints
        "Praxeti White" to "#f5f5f5",
        "Wrack White" to "#e8e8e8",
        "Hexos Palesun" to "#ffd966",
        "Ryza Rust" to "#d56e33",
        "Astorath Red" to "#be2633",
        "Lucius Lilac" to "#a088b5",
        "Skink Blue" to "#3ca2d7",
        "Etherium Blue" to "#85c1e9",
        "Hoeth Blue (Dry)" to "#4d80e6",
        "Imrik Blue" to "#2a6099",
        "Nurgling Green (Dry)" to "#7cb342",
        "Niblet Green" to "#7cc576",
        "Underhive Ash" to "#a8a9a4",
        "Tyrant Skull" to "#cba868",
        "Terminatus Stone" to "#c3b59f",
        "Golgfag Brown" to "#9e652e",
        "Sylvaneth Bark" to "#7a623c",
        "Eldar Flesh" to "#e3b287",
        "Stormfang" to "#7193aa",
        "Longbeard Grey" to "#b9b8b3",
        "Dawnstone (Dry)" to "#7e7f7b",
        "Necron Compound" to "#828d8f",
        "Sigmarite" to "#ecd67f",
        "Golden Griffon" to "#d4af37",
        
        // Technical paints
        "Armageddon Dust" to "#c19a6b",
        "Armageddon Dunes" to "#be8e5f",
        "Agrellan Earth" to "#bb8c6a",
        "Agrellan Badland" to "#ba7950",
        "Martian Ironearth" to "#944c36",
        "Martian Ironcrust" to "#913f2c",
        "Stirland Mud" to "#7d5c42",
        "Stirland Battlemire" to "#6b4c3a",
        "Astrogranite" to "#616769",
        "Astrogranite Debris" to "#535659",
        "Mordant Earth" to "#2f2f2f",
        "Valhallan Blizzard" to "#f8f8ff",
        "Blood for the Blood God" to "#8b0000",
        "Lahmian Medium" to "#f5f5f5",
        "Contrast Medium" to "#f5f5f5",
        "Stormshield" to "#f5f5f5",
        "Ardcoat" to "#f5f5f5",
        "Nurgle's Rot" to "#8a9033",
        "Spiritstone Red" to "#ff0000",
        "Soulstone Blue" to "#0000ff",
        "Waystone Green" to "#00ff00",
        "Nihilakh Oxide" to "#6eb7a9",
        "Typhus Corrosion" to "#5d4f35",
        "Tesseract Glow" to "#4cff00"
    )
    
    // Default colors for each paint type
    private val defaultTypeColours = mapOf(
        "base" to "#3e3e3e",
        "layer" to "#5c8dbd",
        "dry" to "#d9a857",
        "technical" to "#946b54",
        "contrast" to "#aa5599",
        "shade" to "#483d36"
    )
    
    /**
     * Get the color for a paint by name and type
     */
    fun getPaintColour(paintName: String, paintType: String): String {
        return paintColourMap[paintName] ?: defaultTypeColours[paintType] ?: "#cccccc"
    }
    
    /**
     * Get all paint colors as a map
     */
    fun getAllPaintColours(): Map<String, String> {
        return paintColourMap
    }
    
    /**
     * Get default color for a paint type
     */
    fun getDefaultColourForType(type: String): String {
        return defaultTypeColours[type] ?: "#cccccc"
    }
}

// Extension to Application class for dependency injection
val PaintColourServiceKey = AttributeKey<PaintColourService>("PaintColourService")

fun Application.configurePaintColourService() {
    val service = PaintColourService()
    attributes.put(PaintColourServiceKey, service)
}